name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  
  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # Maps / Local
  google_maps_flutter: ^2.9.0
  shared_preferences: ^2.5.3

  # (Eski TTS - şimdilik kalsın, istersen sonra kaldırırız)
  flutter_tts: ^3.8.3

  # ✅ Cloud TTS (internet ile güzel ses)
  http: ^1.2.2
  just_audio: ^0.9.39
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
